name: github-actions
on:
  push:
  pull_request:
    branches:
      - "main"

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive' # Include submodules when checking out the repository

      - name: Initialize submodules
        run: git submodule update --init

      - name: Update submodules
        run: git submodule update --remote

      - name: Compilation Test
        run: make re

      - name: Install CUnit
        if: github.event_name == 'pull_request'
        run: sudo apt-get update && sudo apt-get install -y libcunit1-dev

      - name: Install Valgrind
        run: sudo apt-get update && sudo apt-get install valgrind

      - name: CUnit Tests
        if: github.event_name == 'pull_request'
        run: make re debug=true cunit; make re cunit; make valgrind=true cunit
