name: cpp-linter

on:
  push:
  pull_request:

jobs:
  cpp-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Installation
        run: sudo apt-get install bear cppcheck && pip install pre-commit
      - name: Linter
        run: make linter
      
      - name: Tester
        run: make fclean; make test; make fclean; make debug=true test